package controller;
import java.io.*;
import javax.servlet.*;
import javax.servlet.http.*;
import model.Proton;
import dao.ProtonDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
public class InsertData extends HttpServlet
{
  public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException
  {
    PrintWriter out;
    out = response.getWriter();
    ProtonDAO pd = new ProtonDAO();
    Proton P = new Proton();
    try 
    {
          P = pd.searchByIdProtonMax();
    }
    catch (Exception ex) 
    {
          Logger.getLogger(InsertData.class.getName()).log(Level.SEVERE, null, ex);
    }
    int autoId = P.getId()+1;
    out.println("<HTML>");
    out.println("<head>");
    out.println("<TITLE>Insert Data | Proton Pre School</TITLE>");
    out.println("<link rel=\"stylesheet\" href=\"css/header.css\">");
    out.println("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\">");
    out.println("<link rel=\"stylesheet\" href=\"css/style.css\">");
    out.println("<link rel=\"shortcut icon\" href=\"image/proton_logo.png\" />");
    out.println("<script src=\"js/bootstrap.min.js\"></script>");
    out.println("<script src=\"js/jquery-3.3.1.min.js\"></script>");
    out.println("<script type=\"text/javascript\">var documentTitle = document.title + \" - \";(function titleMarquee(){document.title = documentTitle = documentTitle.substring(1) + documentTitle.substring(0,1);setTimeout(titleMarquee,200);})();</script>");
    out.println("<style>h1,h2,code{font-weight:bold;cursor:pointer;}table{cursor:pointer;}</style>");
    out.println("</head>");
    out.println("<body>");
    out.println("<div class=\"header\">");
    out.println("<div style=\"padding:5px;\">");
    out.println("<a href=\"SignOut.jsp\"><b>Log-out!</b></a>");
    out.println("</div>");
    out.println("<div class=\"text-center\">");
    out.println("<img src=\"image/proton_logo.png\" alt=\"\" width=\"15%\" style=\" padding:10px;\"/>");
    out.println("</div>");
    out.println("<div class=\"progress-container\">");
    out.println("<div class=\"progress-bar\" id=\"myBar\"></div>");
    out.println("</div>");
    out.println("</div>");
    out.println("<div class=\"content\">");
    out.println("<div class=\"container\">");
    out.println("<div class=\"text-center\">");
    out.println("<div class=\"col-sm-2\">");
    out.println("<CODE><A href=\"ProtonPreSchool\">Go to Index Page</A></CODE>");
    out.println("</div>");
    out.println("<div class=\"col-sm-2\">");
    out.println("<CODE><A href=\"UpdateById.html\">Update Data</A></CODE>");
    out.println("</div>");
    out.println("<div class=\"col-sm-2\">");
    out.println("<CODE><A href=\"DeleteById.html\">Delete Data</A></CODE>");
    out.println("</div>");
    out.println("<div class=\"col-sm-2\">");
    out.println("<CODE><A href=\"SearchById.html\">Searching Data</A></CODE>");
    out.println("</div>");
    out.println("<div class=\"col-sm-2\">");
    out.println("<CODE><A href=\"SearchAllStudentA\">View Data</A></CODE>");
    out.println("</div>");
    out.println("<div class=\"col-sm-2\">");
    out.println("<CODE><A href=\"SearchAllDeletedA\">View Deleted Data</A></CODE><br>");
    out.println("</div>");
    out.println("</div>");
    out.println("<h2 class=\"text-center\" style=\"cursor:pointer;\"><u><b>Insert Data - Student Form</b></u></h2>");
    out.println("<div class=\"col-sm-12 text-center\">");
    out.println("<code style=\"cursor:help;\" title=\"Id - "+autoId+" is Auto Generated by system software.\">Student Id AUTO_GENERATED by System Software.</code>");
    out.println("<hr style=\"color:blue;\">");
    out.println("</div>");
    out.println("<form method=\"POST\" action=\"InsertStudent\">");
    out.println("<label for=\"name\">Student Id:</label><span style=\"float:right;color:royalblue;\" title=\"Id - "+autoId+" is Auto Generated by system software.\"><i>ID AUTO-GENERATED BY SYSTEM </i><big style=\"color:red\">*</big></span>");
    out.println("<input type=\"text\" name=\"txtName\" style=\"font-size:25px;cursor:no-drop;font-weight: bold;\" title=\"Id - "+autoId+" is Auto Generated by system software.\" value=\""+autoId+"\" autocomplete=\"off\" disabled/>");
    out.println("<label for=\"name\">Student Name:</label>");
    out.println("<input type=\"text\" name=\"txtName\" placeholder=\"Enter Student Name\" autofocus required autocomplete=\"off\"/>");
    out.println("<label for=\"fname\">Father's Name:</label>");
    out.println("<input type=\"text\" name=\"txtFname\" placeholder=\"Enter Father's Name\" autofocus required autocomplete=\"off\"/>");
    out.println("<label for=\"Std\">Standard / Class:</label>");
    out.println("<input type=\"number\" name=\"txtStd\" placeholder=\"Select Standard / Class\" min=\"1\" max=\"10\" autofocus required autocomplete=\"off\"/>");
    out.println("<label for=\"dob\">Date of Birth:</label>");
    out.println("<input type=\"date\" name=\"txtDob\" autofocus required autocomplete=\"off\"/>");
    out.println("<label for=\"mobile\">Contact:</label>");
    out.println("<input type=\"tel\" name=\"txtMobile\" placeholder=\"Contact number without ISD code.\" maxlength=\"10\" autofocus required autocomplete=\"off\"/>");
    out.println("<label for=\"fee\">Yearly Fee:</label>");
    out.println("<input type=\"number\" name=\"txtFee\" placeholder=\"Amount (in Rs.)\" min=\"1\" max=\"50000\" autofocus required autocomplete=\"off\"/>");            
    out.println("<label for=\"address\">Address:</label>");
    out.println("<textarea width=\"100%\" name=\"txtAddress\" placeholder=\"Permanent Address\" autofocus required autocomplete=\"off\"></textarea>");
    out.println("<input type=\"submit\" value=\"Submit\">");
    out.println("<input type=\"reset\" value=\"Reset\">");
    out.println("</form>");
    out.println("<center>");
    out.println("<CODE><A href=\"ProtonPreSchool\">Go to index page</A></CODE>");
    out.println("</center>");
    out.println("</div>");
    out.println("</div>");
    out.println("</body>");
    out.println("</HTML>");
  }
}